### PR TITLE
Fix issue 41

### LINKED ISSUE #41: gulp end event not firing in 2.0.0
In v1.0.3 I use the gulp 'end' event to shutdown my selenium server:

``` js
return gulp.src('./wdio.conf.js'))
    .pipe(webdriver({
      wdioBin:  path.join(__dirname, 'node_modules', '.bin', wdioCommand)
    })).once('end', () => {
      selenium.child.kill();
    });`
```

however in 2.0.0 the 'end' event never fires. Is this intentional?

### PR DESCRIPTION
**Pull request by azaslavsky**
This resolved #41 for me in my local implementation.  It just forces the stream to explicitly emit its "end" event.  Also fixed a typo in the test spec.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -12,7 +12,9 @@ module.exports = (options) => {
         wdio.run().then(code => {
             process.stdin.pause()
 
-            if (code !== 0) {
+            if (code === 0) {
+                process.nextTick(() => stream.emit('end'))
+            } else {
```
Comment (christian-bromann) [inline src/index.js]: no if required, can't we just execute this after the `callback()` call?

Comment (azaslavsky) [inline src/index.js]: Touche.  I can change it if you like.

**Comment by azaslavsky** [comment]
Ok, should be good to go.

**Comment by christian-bromann** [comment]
Sweet thanks!

**Comment by christian-bromann** [comment]
Released and published!

**Comment by azaslavsky** [comment]
Hmm, so I just pulled 2.0.2 off npm, and the new code still isn't in?  I did `npm cache clean` and everything, so I do think its pulling correctly...

**Comment by christian-bromann** [comment]
Not sure but your code is in that version, see https://github.com/webdriverio/gulp-webdriver/blob/v2.0.2/src/index.js#L22
